### ISSUE TITLE
esedbtools make errors on Kali 2016 Rolling

### ISSUE THREAD

**Issue by Brockway** [pentestgeek/smbexec#127]
After getting past the winexe and smbclient compilation issues by linking to the stock pth versions in Kali, the last hurdle appears to be esedbtools bailing out of its make with a bunch of undefined reference to unicode functions:

tmp/smbexec-inst/libesedb-20120102/libuna/libuna_utf16_string.c:2780: undefined reference to `libuna_unicode_character_copy_from_utf32_stream'
/tmp/smbexec-inst/libesedb-20120102/libuna/libuna_utf16_string.c:2762: undefined reference to `libuna_unicode_character_copy_from_utf16'
collect2: error: ld returned 1 exit status
Makefile:461: recipe for target 'esedbexport' failed
make[1]: *** [esedbexport] Error 1
make[1]: Leaving directory '/tmp/smbexec-inst/libesedb-20120102/esedbtools'
Makefile:503: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
[!] esedbtools didn't install properly. You may need to do it manually

Not finding much initially on what is missing and doesn't look like there is a native version of the esedb libs in kali 2 like there is now w/ pth-winexe and pth-smbclient.

**Comment by hatlord** [comment]
Same issue here, after the fixing the symlinks as per your recommendation! (thanks).

**Comment by dwmuller** [comment]
I have a workaround for the lubuna problem, but it's ugly. The build fails because of incompatibilities between C code in libesedb's copy of libuna and the version of GCC installed. The workaround is to do something like the following before running install.sh, to build esedbtools:

mkdir /tmp/smb-inst
cd /tmp/smb-inst
wget https://googledrive.com/host/0B3fBvzttpiiSN082cmxsbHB0anc/libesedb-alpha-20120102.tar.gz
tar -zxf libesedb-alpha-20120102.tar.gz
cd libesedb-20120102
CFLAGS="-g -O2 -Wall -fgnu89-inline" ./configure --enable-static-executables 
make
mv esedbtools /opt/esedbtools
cd /tmp & rm -rf esedb-inst

After this manual build of esedbtools, the first step of the instructions in the book should work. Although the problem is only in the libuna source code, the CFLAGS override, which asks for legacy inlining behavior, seems to work with the other sources as well.

**Comment by hatlord** [comment]
That does indeed seem to fix it! Ill test it in anger asap.

**Comment by dwmuller** [comment]
Cool. Note that this really ought to be fixed in the libuna sources, makefiles, or autoconf files, but I haven't spend the time figuring out how to do that. I haven't worked with C or makefiles in years, and never worked with autoconf except as a user.

**Comment by Brockway** [comment]
thanks dwmuller.

**Comment by dwmuller** [comment]
You're welcome. BTW, I just noticed that my instructions above contain the phrase "in the book" ... that's because I copied and pasted from an email to the author of The Hacker Playbook 2. I was working through the book's instructions on setting up a pentest environment.

**Comment by manthenavamsi** [comment]
@dwmuller : Thank you for your workaround, installation went well without any errors, but when I run smbexec couple errors occured. I fixed one, but I could not find i686-w64-mingw32-gcc file in /usr/bin to update the path in smbexec.yml.

[!] /usr/bin/i686-w64-mingw32-gcc does not exists, functionality may break. Update smbexec.yml with correct path.

Any idea !!
